name: Deploy emka.exe

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Pobranie kodu źródłowego
      - name: Checkout code
        uses: actions/checkout@v3

      # (Opcjonalnie) Budowanie pliku emka.exe
      - name: Build application
        run: |
          echo "Build step here if needed"
          # Na przykład: msbuild MyApp.sln

      # Przesyłanie pliku emka.exe na serwer docelowy
      - name: Deploy to server
        run: |
          # Zastąp poniższy przykład odpowiednią metodą przesyłania
          scp emka.exe user@your-server:/path/to/deploy/

      # (Opcjonalnie) Uruchamianie aplikacji na serwerze
      - name: Start application
        run: |
          ssh user@your-server "start /b /path/to/deploy/emka.exe"

      # Rejestrowanie wdrożenia w GitHub Deployments
      - name: Mark Deployment in GitHub
        uses: peter-evans/create-or-update-deployment@v2
        with:
          environment: production
          description: Deploying emka.exe to production
          auto_merge: false
          transient_environment: false

