name: Deploy emka.exe from GitHub Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Wybierz środowisko do wdrożenia"
        required: true
        default: "production"
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Pobranie pliku emka.exe z GitHub Releases
      - name: Download emka.exe
        run: |
          curl -L -o emka.exe https://github.com/KonradCode/emerytura/releases/download/2/emka.exe

      # Uruchom skrypt PowerShell
      - name: Run deploy.ps1
        run: |
          powershell -File ./deploy.ps1

      # Sprawdź repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3

