name: Deploy emka.exe from GitHub Release

on:
  workflow_dispatch: # Pozwala uruchomić workflow ręcznie

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Pobranie pliku emka.exe z GitHub Releases
      - name: Download emka.exe
        run: |
          curl -L -o emka.exe https://github.com/KonradCode/emerytura/releases/download/2/emka.exe

      # Przesyłanie pliku na serwer docelowy (przykład z SCP)
      - name: Upload emka.exe to server
        run: |
          scp emka.exe user@your-server:/path/to/deploy/

      # (Opcjonalnie) Uruchamianie aplikacji
      - name: Start application on server
        run: |
          ssh user@your-server "start /b /path/to/deploy/emka.exe"

      # Rejestrowanie wdrożenia w sekcji Deployments
      - name: Mark Deployment in GitHub
        uses: peter-evans/create-or-update-deployment@v2
        with:
          environment: production
          description: Deployed emka.exe from GitHub Release to production
