name: Odpal Emeryture z GitHub Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Wybierz środowisko do wdrożenia"
        required: true
        default: "production"
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Sprawdź repozytorium
      - name: Checkout repository
        uses: actions/checkout@v3
    
      # Pobranie pliku emka.exe z GitHub Releases
      - name: Download emka.exe
        run: |
          curl -L -o emka.exe https://github.com/KonradCode/emerytura/releases/download/2/emka.exe

      - name: List files in working directory
        run: dir

      # Uruchom skrypt PowerShell
      - name: Run deploy.ps1
        run: |
          powershell -File ./deploy.ps1


     # - name: Mark Deployment in GitHub
     #   uses: peter-evans/create-or-update-deployment@v2
     #   with:
     #     environment: production
     #     description: Deployed new version to production
