name: Deploy emka.exe from GitHub Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Wybierz środowisko do wdrożenia"
        required: true
        default: "production"
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Pobranie pliku emka.exe z GitHub Releases
      - name: Download emka.exe
        run: |
          curl -L -o emka.exe https://github.com/KonradCode/emerytura/releases/download/2/emka.exe


      # Rejestrowanie wdrożenia w sekcji Deployments
      - name: Mark Deployment in GitHub
        uses: peter-evans/create-or-update-deployment@v2
        with:
          environment: production
          description: Deployed emka.exe from GitHub Release to production
